### ISSUE TITLE
Doesn't recognize virtual keyboard input / buttons on drawing tablet

### ISSUE THREAD

**Issue by maeblythe** [sdercolin/vlabeler#1]
On Windows 10. Using a tablet PC not in mode S.

The program only recognizes '-' and '=' when using the tablet's default keyboard. All other button presses are ignored.

While the drawing tablet works for moving parameters, the buttons which are mapped to the correct keystrokes are ignored.

The accessibility feature, On Screen Keyboard, does work as intended.

Perhaps adding on screen buttons for next and previous would be helpful.

Video demonstration: https://youtu.be/2h612gV085s

**Comment by sdercolin** [comment]
@maeblythe Thank you for your help on testing and reporting the issue.
I think it's a great idea that every action should be available from menu or button click on screen, so we will add buttons for switching features.
For other actions, such as "scroll to center", you can find them in the Edit menu.

For the issue that keys are not working, please kindly help use diagnose the problem by:
1. Download the app from https://drive.google.com/file/d/1BXH39n-O28gUkusA3pyXx2akTCv2GtYr/view?usp=sharing . It's a version based on the recent release 1.0.0-alpha2 version with some code added, to print the received keyboard events to logs.
2. After opening a project, press the used keys including Down, Ctrl, F etc
3. Find the logs from the vLabeler directory, probably "C:\Users\<your_user_name>\vLabeler\logs\info.log", and upload it here. (Or to my e-mail address: sder.colin@gmail.com)

**Comment by sdercolin** [comment]
https://github.com/sdercolin/vlabeler/compare/62b845d..2066eb9
