### ISSUE TITLE
Batch editing of oto.ini

### ISSUE THREAD

**Issue by adlez27** [sdercolin/vlabeler#10]
I had previously been planning to create a batch editor for OTO.ini as a web application, but it may be more useful to incorporate this directly into an OTO.ini editor like vLabeler. This suggestion is based on my development plans. Since I'm not sure whether I can commit to adding this feature myself, any developer is welcome to work on this.

## Specifications
A batch editing preset would consist of
- A list of user-specified rules (applied to the oto in order)
- A final rule for handling duplicate aliases (applied after user-specified rules)

A few useful presets to include by default would be adding a suffix to all aliases, adding hiragana to a romaji voicebank (and vice versa), and changing the tempo of all oto lines.

### User-specified rules
A user-specified rule would consist of
- How to select lines
- How to edit alias or how to edit parameters

A rule could edit aliases only, edit parameters only, or edit both aliases and parameters.
#### Selecting lines
These are the options for selecting lines.
- Select 1 specific line of the oto.ini
- Select all lines of the oto.ini
- Select lines where the alias matches a regex
- Select lines where the filename matches a regex
- Select lines where the alias and filename match regexes
#### Editing aliases
After selecting lines, these actions could be applied
- Delete the lines
- Replace the alias using a regex
- Make a copy of the line and set the new alias with a regex
#### Editing parameters
After selecting lines, these actions could be applied
- Change the values of parameters (set equal to x, or add/subtract/multiply/divide original value with x)
- Recalculate parameters according to tempo change (user specifies which parameters will change)
- Calculate 1 parameter from another parameter (eg. set preutterance to be 2x overlap)
### Duplicate alias rule
Duplicate aliases are lines of the OTO where the alias is EXACTLY the same. These are the options for handling them.
- Do nothing
- Add number to the end of all duplicate aliases (ka, ka1, ka2, ka3, etc.)
- Add number to the first X duplicates, then delete the rest (eg. if the limit is 2, then keep "ka" and "ka1", and delete the rest)
- Delete all duplicates
## Old mockup
This mockup was designed for the previous plan of making a web app. vLabeler can use this as inspiration, but it does not need to match exactly.

![find all](https://i.imgur.com/z7CnWKf.png)  
![find alias](https://i.imgur.com/ElgRMfr.png)  
![alias](https://i.imgur.com/q1vzvax.png)  
![parameter value](https://i.imgur.com/jlfYRw7.png)  
![parameter tempo](https://i.imgur.com/CJ9CdDk.png)  
![parameter calculate](https://i.imgur.com/JV56o7U.png)  
![dupes](https://i.imgur.com/AMtiJyN.png)

**Comment by sdercolin** [comment]
Impressive!

I think we can divide the processes into different macro edit plugins such "Edit Names" and "Edit paramters".
The selecting part can be implemented as common API for any macro edit plugin with some complicated UI (like a filter list and a preview of selected lines)

For duplication, it may be easier to handle in a template generator plugin.

**Comment by adlez27** [comment]
Thank you. While most users will probably only need to do simple edits, the more complex features are based on things I do while writing base OTOs manually in a text editor.

For instance, I might have a reclist.txt file that looks like this.
```
sa-sa-s
se-se-s
na-na-n
no-no-n
```

Using the regex Find+Replace in the text editor, I set the fields to this.

Find:
```
^(.)(.)-..-.$
```

Replace:
```
$1$2-$1$2-$1.wav=- $1$2,90,210,-830,110,10
$1$2-$1$2-$1.wav=$2 $1,840,170,-260,160,80
$1$2-$1$2-$1.wav=$1$2,1000,200,-920,100,50
$1$2-$1$2-$1.wav=$2 $1-,1840,180,0,160,80
```

After running the Find+Replace operation, the reclist is transformed into an oto.ini that looks like this.
```
sa-sa-s.wav=- sa,90,210,-830,110,10
sa-sa-s.wav=a s,840,170,-260,160,80
sa-sa-s.wav=sa,1000,200,-920,100,50
sa-sa-s.wav=a s-,1840,180,0,160,80

se-se-s.wav=- se,90,210,-830,110,10
se-se-s.wav=e s,840,170,-260,160,80
se-se-s.wav=se,1000,200,-920,100,50
se-se-s.wav=e s-,1840,180,0,160,80

na-na-n.wav=- na,90,210,-830,110,10
na-na-n.wav=a n,840,170,-260,160,80
na-na-n.wav=na,1000,200,-920,100,50
na-na-n.wav=a n-,1840,180,0,160,80

no-no-n.wav=- no,90,210,-830,110,10
no-no-n.wav=o n,840,170,-260,160,80
no-no-n.wav=no,1000,200,-920,100,50
no-no-n.wav=o n-,1840,180,0,160,80
```

I am not sure if a simplified template generator would work for this purpose, because the flexibility of using regex patterns is a method used for completely custom reclists rather than common standardized reclists. But if this is still possible with the planned features you have in mind, that would be much appreciated.

**Comment by sdercolin** [comment]
I think this can be handled with the current template generator plugin,
you can define a `string` param to take the regex (and other data you need).
The reclist is provided as a list of the sample wav files in the folder.

However it's quite difficult for most users to write something like
```
^(.)(.)-..-.$
```
and 
```
$1$2-$1$2-$1.wav=- $1$2,90,210,-830,110,10
$1$2-$1$2-$1.wav=$2 $1,840,170,-260,160,80
$1$2-$1$2-$1.wav=$1$2,1000,200,-920,100,50
$1$2-$1$2-$1.wav=$2 $1-,1840,180,0,160,80
```
so I think it's better to contain those logics in the generator's script and only takes the values as paramter (default values are required). In this way we will have a CVVC template generator for this type of reclist.

Of course we can have a generator taking the regex and entry lines template for some advanced users as well because it's highly customizable.

**Comment by adlez27** [comment]
An advanced user mode would be great!

**Comment by sdercolin** [comment]
`(.)(.)-\1\2-.` may work better..
<img width="388" alt="image" src="https://user-images.githubusercontent.com/7665216/180750754-3671a3fe-4d40-47cd-85b6-f14871c9e8a0.png">

**Comment by sdercolin** [comment]
As we cannot expect all files are like `sa-sa-a`
`(.)(.)-\1\2-\1` may work better.


<img width="248" alt="image" src="https://user-images.githubusercontent.com/7665216/180750844-571633d8-a4de-4d10-8526-721b29d62593.png">

**Comment by adlez27** [comment]
The idea behind using regex is to be able to fully customize the pattern to any arbitrary string. I used "sa-sa-s" as an example earlier, but these are a few real lines from an actual custom reclist I've written.

```
a-pa-ba-ta-p
e-de-ke-ge-b
i-'i-chi-ji-t
o-fo-vo-tho-d
u-dhu-su-zu-k
A-shA-zhA-hA-g_
I-mI-nI-ngI-ch_
U-lU-rU-rrU-j_
```

I was able to match such unusual strings with the pattern `(.)-(.{1,2}).-(.{1,2}).-(.{1,2}).-(.{1,2})(_?)` and then create all necessary OTO lines for them at once. Hopefully something like that would still be possible in the advanced user mode.

**Comment by sdercolin** [comment]
Added plugins [batch-edit-entry-name](https://github.com/sdercolin/vlabeler/tree/1.0.0-alpha14/resources/common/plugins/macro/batch-edit-entry-name) and [batch-edit-oto-parameter](https://github.com/sdercolin/vlabeler/tree/1.0.0-alpha14/resources/common/plugins/macro/batch-edit-oto-parameter) to cover `batch edit` needs.

Also we have a [regex-raw-gen](https://github.com/sdercolin/vlabeler/tree/1.0.0-alpha14/resources/common/plugins/template/regex-raw-gen) template generator to handle the following need.

> Thank you. While most users will probably only need to do simple edits, the more complex features are based on things I do while writing base OTOs manually in a text editor.
> 
> For instance, I might have a reclist.txt file that looks like this.
> 
> ```
> sa-sa-s
> se-se-s
> na-na-n
> no-no-n
> ```
> 
> Using the regex Find+Replace in the text editor, I set the fields to this.
> 
> Find:
> 
> ```
> ^(.)(.)-..-.$
> ```
> 
> Replace:
> 
> ```
> $1$2-$1$2-$1.wav=- $1$2,90,210,-830,110,10
> $1$2-$1$2-$1.wav=$2 $1,840,170,-260,160,80
> $1$2-$1$2-$1.wav=$1$2,1000,200,-920,100,50
> $1$2-$1$2-$1.wav=$2 $1-,1840,180,0,160,80
> ```
> 
> After running the Find+Replace operation, the reclist is transformed into an oto.ini that looks like this.
> 
> ```
> sa-sa-s.wav=- sa,90,210,-830,110,10
> sa-sa-s.wav=a s,840,170,-260,160,80
> sa-sa-s.wav=sa,1000,200,-920,100,50
> sa-sa-s.wav=a s-,1840,180,0,160,80
> 
> se-se-s.wav=- se,90,210,-830,110,10
> se-se-s.wav=e s,840,170,-260,160,80
> se-se-s.wav=se,1000,200,-920,100,50
> se-se-s.wav=e s-,1840,180,0,160,80
> 
> na-na-n.wav=- na,90,210,-830,110,10
> na-na-n.wav=a n,840,170,-260,160,80
> na-na-n.wav=na,1000,200,-920,100,50
> na-na-n.wav=a n-,1840,180,0,160,80
> 
> no-no-n.wav=- no,90,210,-830,110,10
> no-no-n.wav=o n,840,170,-260,160,80
> no-no-n.wav=no,1000,200,-920,100,50
> no-no-n.wav=o n-,1840,180,0,160,80
> ```
> 
> I am not sure if a simplified template generator would work for this purpose, because the flexibility of using regex patterns is a method used for completely custom reclists rather than common standardized reclists. But if this is still possible with the planned features you have in mind, that would be much appreciated.
