### ISSUE TITLE
Entries list filter will be reset after clicking any entry

### ISSUE THREAD

**Issue by ghosrt** [sdercolin/vlabeler#11]
- Version: 1.0.0-alpha10
- Platform: Windows 11 x64 build 22000
- Reproduce steps
  1. Load an existing UTAU library
  2. Wait after the entries list is loaded.
  3. Pin Entry List and then do a entry filter.
  4. Click on any entry filtered.
- Expected result
  - The filter should be kept even after clicking on any entry.
- Actual Result: 
  - The filter will be resetted and return to all entries list.
  - However the filter keyword is not being cleared.

**Comment by sdercolin** [comment]
Fixed in: https://github.com/sdercolin/vlabeler/releases/tag/1.0.0-alpha11

**Comment by ghosrt** [comment]
Confirmed with 1.0.0-alpha11. The entries list is now being locked after selection.
However, the waveform/spectrogram is not updated even if the user changes their selected item. 😿

**Comment by sdercolin** [comment]
Fixed~ https://github.com/sdercolin/vlabeler/releases/tag/1.0.0-alpha12
