### ISSUE TITLE
Add tabs for multiple open projects

### ISSUE THREAD

**Issue by nagotown** [sdercolin/vlabeler#12]
I'm thinking of a feature where you could have multiple projects open as tabs for quicker editing.
Thinking there could also be a kind of project to remember each of the "sub" projects so you don't have to reopen them every time.
Here's how the layout for how it could be (just drew over the app)
![image](https://user-images.githubusercontent.com/35883871/184428269-246c274c-a296-4765-a417-8dbd641e174e.png)

**Comment by sdercolin** [comment]
Released on the latest version
