### ISSUE TITLE
Values are set to max integer value if sample is too long

### ISSUE THREAD

**Issue by Zestea** [sdercolin/vlabeler#13]
While labeling a sample just under 4 minutes long, I exported the .lab file and noticed that the last couple of entries for that specific sample all had starting and ending values of 2147483648, which is roughly the max integer value. Looking at the project file in a text editor, those same entries all showed up with correct values before being converted to a .lab format. I've attached the related files.
[0139.zip](https://github.com/sdercolin/vlabeler/files/9398400/0139.zip)

**Comment by sdercolin** [comment]
Thank you for the report!
I have fixed the problem and it will be available in the next release.
https://github.com/sdercolin/vlabeler/commit/bb93d12300543439c58d1c5a5aa2cb89edcaf0fd
