### ISSUE TITLE
relative working directory

### ISSUE THREAD

**Issue by SeleDreams** [sdercolin/vlabeler#16]
Hi, I was wondering if there's a way to have a relative working directory with vlabeler ? I feel like this can make it easier to share vlabeler projects on multiple computers and to move the projects

**Comment by sdercolin** [comment]
`Project.workingDirectory` should be automatically updated if you move the project file to another place.

What's the problem you are facing now?

**Comment by SeleDreams** [comment]
When I tried to open my project made on windows on my linux pc, vlabeler just closed,manually changing the paths to the linux paths directly in the project file kind of fixed it as it didn't crash however it ended up having weird effects where it asks me to specify the path, but instead of a directory selection, the OS popup that appears is a *file* selection popup so in the end it never works because it forces me to select a file, so even if i select a wav it won't select the directory and won't work

**Comment by SeleDreams** [comment]
seems like i end up being able to work with it after manually changing all path instances of the project file, but yeah i think vlabeler should be able to directly know where the samples are from the location of the project file itself

**Comment by sdercolin** [comment]
> When I tried to open my project made on windows on my linux pc, vlabeler just closed,

Probably because Windows uses different separator `\` from linux/mac's `/`. Didn't really test this case, will look later

> it never works because it forces me to select a file, so even if i select a wav it won't select the directory and won't work
On linux, the file chooser can only choose file (see [Known Issues 3](https://github.com/sdercolin/vlabeler#known-issues)). If it doesn't work, it should be some sort of bug (will fix it)

> vlabeler should be able to directly know where the samples are from the location of the project file itself
Some users don't want the project file inside their voicebank folders, so we used the absolute paths.
I think we can have an option while creating projects, to allow saving relative paths of sample folders instead.

**Comment by SeleDreams** [comment]
> > When I tried to open my project made on windows on my linux pc, vlabeler just closed,
> 
> Probably because Windows uses different separator `\` from linux/mac's `/`. Didn't really test this case, will look later
> 
> > it never works because it forces me to select a file, so even if i select a wav it won't select the directory and won't work
> 
> On linux, the file chooser can only choose file (see [Known Issues 3](https://github.com/sdercolin/vlabeler#known-issues)). If it doesn't work, it should be some sort of bug (will fix it)
> 
> > vlabeler should be able to directly know where the samples are from the location of the project file itself
> 
> Some users don't want the project file inside their voicebank folders, so we used the absolute paths. I think we can have an option while creating projects, to allow saving relative paths of sample folders instead.

i think a simple way would be that if the paths specified are under the project path then it would use the syntax starting with ./ and ./ would indicate that it's a relative file

**Comment by sdercolin** [comment]
Maybe yes, we can only handle the cases where the project file is **inside** the `Sample Directory`

**Comment by sdercolin** [comment]
@SeleDreams hello, I have implemented this.
Could you please try this build to see if all your problems are solved?
https://github.com/sdercolin/vlabeler/releases/tag/1.0.0-beta5-test1
