### ISSUE TITLE
1.0.0-beta-15 (Compose 1.3.1) doesn't launch on macOS

### ISSUE THREAD

**Issue by CloudyLikesVocal-Synths** [sdercolin/vlabeler#23]
vLabeller wont open and I don't know why.

**Comment by sdercolin** [comment]
Please provide your logs. They should be under `C:\Users\<your_user_name>\vLabeler\.logs`.

**Comment by SeleDreams** [comment]
I think the beta 15 broke vlabeler on mac, I did a test, it works on 14 but doesn't on 15
I checked the logs, doesn't seem like anything out of the ordinary got reported

**Comment by sdercolin** [comment]
@SeleDreams Thank you for the info! It would cost some time to find a solution, so currently please use beta14 on macOS.

**Comment by CloudyLikesVocal-Synths** [comment]
Oh ok thank you!

**Comment by CloudyLikesVocal-Synths** [comment]
Yup it worked! Tysm!

**Comment by SeleDreams** [comment]
I don't think it should be marked as completed yet, a workaround has been found by using beta 14 but it is'lt an actual fix, it most likely should be closed once a fix will be released

**Comment by sdercolin** [comment]
Yes. Let me reopen this and change the title.

**Comment by sdercolin** [comment]
We have to choose a stable Compose version for the formal release later.

Some notes about known issues with different Compose versions:

### 1.2.2
Crash on the scroll bar inside the project creator: https://github.com/sdercolin/vlabeler/commit/b17485415d8158c40c7aba566aecb02075e2dae8

Workaround: Remove the scroll bar, but then it may not be able to show all contents when the window is small.

### 1.3.0~1.3.1
Cannot launch on macOS: https://github.com/JetBrains/compose-multiplatform/issues/2867

### 1.4.0
Frequent freezing when switching entries and rendering graphs: https://discord.com/channels/984044285584359444/989195885512646746/1116343948726763581

# 1.4.1 (latest)
The freezing issue from 1.4.0 may still occur. WIP investigating.
https://discord.com/channels/984044285584359444/1116345125099028552/1123611861720498216

**Comment by sdercolin** [comment]
1.0.0-beta16 released.
