### ISSUE TITLE
vLabeler beta17 crashing on adjusting entry length

### ISSUE THREAD

**Issue by KluelessKisa** [sdercolin/vlabeler#27]
Hello!
I'm using NNSVS default labeler to label a DiffSinger sample base by custom set of phonemes. My usual workflow is to use a cutting tool, name the entry and if the length doesn't quite fit, I use the Cursor tool to adjust it back or forth.

It was of no issue with beta16, but attempting to do the same with beta17 yields a crash I managed to screenshot. 

I use a custom spectrogram map and have most autoscrolling disabled for my convenience.

Let me know what else needs to be submitted for the issue to be resolved.
![vlabel-17-crash](https://github.com/sdercolin/vlabeler/assets/143886262/cc66e4a1-2394-458d-a4e0-5a195c126663)

**Comment by sdercolin** [comment]
Thank you for your quick report!
This is a critical issue, so we have fixed it and released beta18, please update the app.
Sorry for the inconvenience.

Best,
sdercolin
