### ISSUE TITLE
Disable Preutterance moving entire oto position

### ISSUE THREAD

**Issue by nagotown** [sdercolin/vlabeler#3]
Add the feature to stop moving Preutterance from moving every parameter(?)
Could probably go in a preferences area.

**Comment by sdercolin** [comment]
Acutally you can edit the `oto.default.labeler.json` file:
```json
  "lockedDrag": {
    "useDragBase": true, // set to false to disable Preutterance as the primary param
    "useStart": false // set to true if you want to move all when dragging "start"
  },
```

UI configuration will be implemented in the future.
