### ISSUE TITLE
無法 为 UTAU 歌手添加文件夹作为子项目

### ISSUE THREAD

**Issue by tooruche520** [sdercolin/vlabeler#36]
**Describe the bug**
無法 为 UTAU 歌手添加文件夹作为子项目

**To Reproduce**
1. 新建一個 `UTAU singer 标注器` 的項目
2. `工具` -> `批量編輯` -> `为 UTAU 歌手添加文件夹作为子项目`
3. 選擇資料夾後按 `執行`
4. 出錯了QQ

**Expected behavior**
可以成功新增UTAU歌手的子項目tab

**Screenshots**
<img width="923" alt="image" src="https://github.com/sdercolin/vlabeler/assets/108397417/1949e5c6-7a86-4d58-908d-646909888c85">
<img width="470" alt="image" src="https://github.com/sdercolin/vlabeler/assets/108397417/33d05f55-c998-4f39-bbf9-1bad8fce6f29">
<img width="923" alt="image" src="https://github.com/sdercolin/vlabeler/assets/108397417/663a4b7f-96f1-4e91-acf7-095f74dcb890">

**App runtime Info**
App version: 1.2.0
Runtime version: 17.0.9+8-LTS
OS: Windows 11 10.0 amd64
System locale: zh_TW
Debug mode: false
User directory: C:\Users\willi\vLabeler
Resource directory: C:\Users\willi\Documents\vlabeler-1.2.0-win64\app\resources
Tracking id: cae0401e-6108-4c9b-a184-11bb840f2120

**Logs**
[info.log](https://github.com/sdercolin/vlabeler/files/14761379/info.log)
[error.log](https://github.com/sdercolin/vlabeler/files/14761374/error.log)

**Comment by sdercolin** [comment]
@tooruche520 Thank you for the report! We will include the fix in the next release version.
Right now please use this plugin instead: 
[utau-add-folder-temp-fix.zip](https://github.com/sdercolin/vlabeler/files/14776093/utau-add-folder-temp-fix.zip)

**Comment by tooruche520** [comment]
太感謝了！它順利運作了！但我想推薦一個功能：
在 UTAU singer labeler 上新增子項目時，可以選擇我想要的 oto 模板。就像新建一個 UTAU oto labeler 的項目一樣。不會只是單純把音頻文件導入。

##### 順利新增子項目，但沒有可以選擇要的 oto 模板🥺
<img width="600" alt="image" src="https://github.com/sdercolin/vlabeler/assets/108397417/78ce0db5-9e05-4fa9-816c-94a69876f420">

##### 新建一個 UTAU oto labeler 的項目時選擇想要的 oto 模板 (舉例圖片)
<img width="600" alt="image" src="https://github.com/sdercolin/vlabeler/assets/108397417/e8563399-56ed-441a-8332-c94c13268487">


如果已經有類似的功能，請麻煩告訴我，很抱歉提出愚蠢的問題。

**Comment by sdercolin** [comment]
我们有在考虑做类似的功能，到时候应该会代替这个插件。
现在的话，可以尝试针对整个声库重新建立项目，并且用"文件"->"导入"功能来将新/旧的其中一个项目导入到另一个，从而起到合并的效果。
