### ISSUE TITLE
When building vLabeler from source code on Arch Linux, the menu bar cannot display properly.

### ISSUE THREAD

**Issue by la1den** [sdercolin/vlabeler#38]
**Describe the bug**
After building the project according to the documentation, the menu bar displays incorrectly.

**To Reproduce**
1. `cd vLabeler`
2. `./gradlew createDistributable`
3. `cd build/compose/binaries/main/app/vLabeler/bin/`
4. `./vLabeler`

**Expected behavior**
The menu bar displays correctly.

**Screenshots**

https://github.com/sdercolin/vlabeler/assets/55609004/0188e4e2-3d79-448c-b5c3-442369f3c2c6

**App runtime Info**
App version: 1.2.0
Runtime version: 17.0.11+9
OS: Linux 6.6.28-2-lts amd64
System locale: zh_CN
Debug mode: false
User directory: /home/lfh/vLabeler
Resource directory: /media/sda1/data/code/vlabeler-1.2.0/build/compose/binaries/main/app/vLabeler/lib/app/resources
Tracking id: null

**Logs**

[error.log](https://github.com/sdercolin/vlabeler/files/15142451/error.log)
[info.log](https://github.com/sdercolin/vlabeler/files/15142452/info.log)

**Comment by la1den** [comment]
Is it necessary to have other dependencies besides needing JDK 17+ to build successfully? I tried directly unpacking the Ubuntu deb package from the release and it runs normally.

**Comment by sdercolin** [comment]
How about ./gradlew run ?

**Comment by la1den** [comment]
> ./gradlew run

Coping with the same problem.

> ./gradlew packageDistributionForCurrentOS

Output:

> > Task :packageDeb FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':packageDeb'.
> > External tool execution failed:
>   * Command: [/usr/lib/jvm/java-17-openjdk/bin/jpackage, @/media/sda1/data/code/vlabeler-1.2.0/build/compose/tmp/packageDeb.args.txt]
>   * Working dir: []
>   * Exit code: 1
>   * Standard output log: /media/sda1/data/code/vlabeler-1.2.0/build/compose/logs/packageDeb/jpackage-2024-04-29-08-00-03-out.txt
>   * Error log: /media/sda1/data/code/vlabeler-1.2.0/build/compose/logs/packageDeb/jpackage-2024-04-29-08-00-03-err.txt
> 
> BUILD FAILED in 3s
> 9 actionable tasks: 2 executed, 7 up-to-date

[out.txt](https://github.com/sdercolin/vlabeler/files/15144280/jpackage-2024-04-29-08-00-03-out.txt)
[err.txt](https://github.com/sdercolin/vlabeler/files/15144281/jpackage-2024-04-29-08-00-03-err.txt)

I think it might be because I'm not using an Ubuntu system, so I can't build a .deb package.

**Comment by la1den** [comment]
I tried installing a GNOME desktop environment for my system and rebuilt vLabeler. vLabeler runs fine under GNOME, perhaps this is a bug with KDE.

**Comment by sdercolin** [comment]
Sorry I'm not familiar with linux systems and I'm glad you find a solution!
