### ISSUE TITLE
Pressing key while switching window could cause it stack in active

### ISSUE THREAD

**Issue by RibosomeK** [sdercolin/vlabeler#39]
**Describe the bug**
Pressing key while switching to other windows could keep that key active even when you are not pressing it. I will using alt+tab as the example to describe the bug. But other keys like ctrl also reproduce the bug.
如果在按着快捷键同时切换了窗口可能会导致该快捷键一直生效。以下会用 alt+tab 来进行说明，其他按键例如 ctrl 也可以复现该 bug。
 
While using keyborad shortcut (alt+tab) to switch between vlabeler other windows and switch back on Windows, audio preview would automatically play while dragging label lines without pressing alt （cause the defualt key combo is alt+right click).
在 Windows 上用快捷键 alt+tab 切换窗口再切回来的时候，预览播放可能会在没有按下 alt 时在拖动标记时生效。

**To Reproduce**
1. vlabeler is the current active window. 当前窗口为 vlabeler
2. using alt+tab to switch to other app. 按 alt+tab 切换到别的窗口
3. switch back using either alt+tab or mouse. 再用 atl+tab 或者鼠标切换回来
4. dragging lable lines only and it's playing. 拖动标记能听到预览播放

**Expected behavior**
The key being pressed while switching windows should not be active when swich back and release.
安下的按键在切换窗口后再切回来并没有按着的时候不应该保持在被按下的状态

**Screenshots**

**App runtime Info**
App version: 1.2.0
Runtime version: 17.0.9+8-LTS
OS: Windows 11 10.0 amd64
System locale: en_US
Debug mode: false
User directory: C:\Users\Ria\vLabeler
Resource directory: C:\Program Files\vlabeler-1.2.0-win64\app\resources
Tracking id: null

**Logs**
Please find the latest logs and upload them.
- info.log 
[info.log](https://github.com/sdercolin/vlabeler/files/15251314/info.log)
- error.log 
[error.log](https://github.com/sdercolin/vlabeler/files/15251313/error.log)

**Comment by sdercolin** [comment]
Thank you for reporting!
Fixed it in: https://github.com/sdercolin/vlabeler/commit/ee2916a58c74e1d1e2df8b01d912347ec511bd9d
Will be released recently
