### ISSUE TITLE
Render resampler playback for oto entry [UTAU]

### ISSUE THREAD

**Issue by nagotown** [sdercolin/vlabeler#4]
Add the feature to play what an oto entry would sound like in UTAU.
SetParam has this feature, it's triggered by pressing F10 on the keyboard.
This makes it easier to tell if your oto entry is correctly configured without having to open UTAU or reload voicebanks.
As for a resampler that's crossplatform that it could use by default, [macres](https://github.com/titinko/macres) should be ok.

**Comment by sdercolin** [comment]
@nagotown Hello, I want to know more about this idea.
What's the actual difference between the current `entry playback` and this thing?
It seems like resampler only changes the pitch..

**Comment by nagotown** [comment]
mostly timing and checking for errors in the oto, like if the consonant is leaking into vowel and stuff like that.

**Comment by sdercolin** [comment]
Yes, but I wonder why you cannot do that with the current entry playback, and why you can do it with F10 in setParam.
Is it not playing the `Left ~ Right` range?

**Comment by nagotown** [comment]
it does play but you can't hear how it sounds with engine noise without opening UTAU.

**Comment by sdercolin** [comment]
released in 1.0.0-beta4
