### ISSUE TITLE
File not opening, even when using compatible file types

### ISSUE THREAD

**Issue by B3eper132** [sdercolin/vlabeler#43]
**Describe the bug**
since I am working on a private UTAU voicebank, I wanted to use this for oto-ing. The problem is that the files WON'T SHOW UP.

**To Reproduce**
For context, I used Software Automatic Mouth for the samples, so I used [Sebastian Macke's repo](https://github.com/s-macke/SAM) to make the files.
When I opened the folder using the UTAU templates, the files wouldn't appear.
New Project> use Singers/SAM CV for folder> Categorize as an UTAU project> Error saying the does not exist or in the format. 
I am pretty sure the wav files are there
**Screenshots**
![image](https://github.com/sdercolin/vlabeler/assets/145614528/42937ff9-c323-4d1f-a607-814171096d14)
The proof it exists
![image](https://github.com/sdercolin/vlabeler/assets/145614528/80f9b2fc-2372-46d1-9602-51d7486a07d7)
Proof it works with other voicebanks (looking at Adachi Rei's)
![image](https://github.com/sdercolin/vlabeler/assets/145614528/11341d8a-2a44-45bf-9fc4-077a0dacc32d)
Yet I have issues.
**App runtime Info**
App version: 1.3.0
Runtime version: 17.0.11+9-LTS
OS: Windows 10 10.0 amd64
System locale: en_US
Debug mode: false
User directory: \vLabeler
Resource directory: \OpenUtau-win-x64\vLabeler\app\resources
Tracking id: 3bacd6ea-2988-4814-929b-3d27ffe07ed8
**Logs**
- [info.log](https://github.com/user-attachments/files/16117502/info.log)
- [error.log](https://github.com/user-attachments/files/16117501/error.log)

**Comment by sdercolin** [comment]
Could you share any one of the wav file?

**Comment by B3eper132** [comment]
I can through Drive: [e.wav](https://drive.google.com/file/d/1chWt90JK8wFxrASTNvhzkgZhGDzrUH14/view?usp=drive_link)

**Comment by B3eper132** [comment]
I think it might be weird internal encoding causing the program to deny the files since the SAM repo was not updated in a good while, and it causes the WAV files to be incompatible.
(either that or the absence of gaps in the audio causes the program to brick itself)
In case you are wondering, here is how I generated the file just in case
(through a batch file)
sam -sing -speed 72 -pitch 52 -wav e.wav -phonetic EHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEHEH

**Comment by sdercolin** [comment]
I requested the access, please have a look

**Comment by B3eper132** [comment]
go check

**Comment by sdercolin** [comment]
The format is: `PCM_UNSIGNED 22050.0 Hz, 8 bit, mono, 1 bytes/frame`
The `PCM_UNSIGNED` encoding is not supported...
Please try using other audio editing softwares to change the encoding to `PCM_SIGNED` before using. (I think UTAU does not support that either)

**Comment by B3eper132** [comment]
Thanks for letting me know!
<3
