### ISSUE TITLE
"No wav files found" despite there clearly being wav files

### ISSUE THREAD

**Issue by datenroute** [sdercolin/vlabeler#47]
I have been trying to label an utau port diffsinger voicebank as a test, but every time I try to create a project I meet this error: Labeler runtime error when constructing project: No wav files found in the wav folder, please check the wav folder name in labeler settings.

This has never happened before, so I expected it to create the project normally. 

I tried both my Windows PC and my MacBook. Both had the same exact error message.

Currently on my MacBook, here is the info:
App version: 1.3.1
Runtime version: 17.0.11+9-LTS
OS: Mac OS X 13.1 x86_64
System locale: en_JP
Debug mode: false
User directory: /Users/(My real name)/Library/vLabeler
Resource directory: /Applications/vLabeler.app/Contents/app/resources
Tracking id: null

**Logs**
[error.log](https://github.com/user-attachments/files/16987532/error.log)- error.log
[info.log](https://github.com/user-attachments/files/16987538/info.log)

**Comment by sdercolin** [comment]
As the message says, please check the labeler settings. There should be a folder name setting field.

**Comment by datenroute** [comment]
The folder names are the exact same as the settings, so I'm confused.
![Image 2024-09-13 at 6 41](https://github.com/user-attachments/assets/05d9ff9a-ec81-48b1-baba-79ad7e24a684)
<img width="786" alt="Screenshot 2024-09-13 at 6 44 46" src="https://github.com/user-attachments/assets/11fcabca-8b90-4315-b76f-82ab7580a22f">
<img width="658" alt="Screenshot 2024-09-13 at 6 45 18" src="https://github.com/user-attachments/assets/faf1784a-d9ac-4d00-8797-a882c51e3e5b">

**Comment by sdercolin** [comment]
You need to set the sample directory to the folder that contains wav and lab folders, not the wav folder itself.

**Comment by sdercolin** [comment]
Please check README for details.
![image](https://github.com/user-attachments/assets/7aaf4a5b-9914-49e8-b66f-e98a8645b316)

**Comment by datenroute** [comment]
Just realized and yeah that was my mistake. Thank you! It's working now
