### ISSUE TITLE
F0 and Power views of the audio file

### ISSUE THREAD

**Issue by VocAddict** [sdercolin/vlabeler#5]
Not sure if you already have this in the plans but being able to see the pitch as well as the power (dB) of the file helps a lot when otoing, especially when they're not the best in terms of recording. Screenshot of oremo (should also be in setparam but mine refuses to open) below to give an idea of what I'm talking about.

![image](https://user-images.githubusercontent.com/7100190/176173144-bef3713c-2485-4259-953c-5db9c66dbabd.png)

**Comment by sdercolin** [comment]
Released 
https://github.com/sdercolin/vlabeler/releases/tag/1.3.0-beta3
