### ISSUE TITLE
Preutterance will not move to desired position

### ISSUE THREAD

**Issue by mmemey** [sdercolin/vlabeler#52]
Preutterance label will not move in the editor past a certain point, seemingly on random files. Can't seem to find a pattern between files that work fine and those that don't. I can manually fix by writing in the oto.ini file or setparam editor, but that's not ideal obviously. Error log seems to be empty but I attached it anyway, just in case.
 
Video of me trying to move the label, both with cursor and keybind, on bugged files.
https://github.com/user-attachments/assets/98393456-d7b6-4baa-87e9-a11ad1570e95

App version: 1.4.0
Runtime version: 17.0.13+11-LTS
OS: Windows 11 10.0 amd64
System locale: en_US
Debug mode: false
User directory: C:\Users\k\vLabeler
Resource directory: C:\Users\k\Desktop\vlabeler-1.4.0-win64\app\resources
Tracking id: null

[error.log](https://github.com/user-attachments/files/17788107/error.log)
[info.log](https://github.com/user-attachments/files/17788108/info.log)

**Comment by sdercolin** [comment]
Hello, I checked your video, it looks like your end line (right blank/cutoff) is very close to the end of the file's end, so there is not a lot of space for you to move the preutterance, as you are trying to move all the parameters together, and the end line could not be moved out of the audio's range.

**Comment by mmemey** [comment]
My bad, that fixed it right up! Thank you!
