### ISSUE TITLE
Vlabeler freezes when you accidentally scroll to an undefined .wav in pre-filled oto.ini

### ISSUE THREAD

**Issue by KrankerApfel** [sdercolin/vlabeler#8]
I wanted to test vlabeler on a voicebank for which I have not yet finished recording all the .wav files.
I'm using a pre-filled oto.ini and so some lines refer to non-existent .wav files.

When I scroll to select a line to edit and I go through a line that refers to a non-existent .wav, an error is displayed and vlabeler crashes (impossible to close the window or doing anything).

Using a try/catch instead of a fatal error could be better, or maybe put those lines in grey so we can't accidentally scroll on it.

P.S : thank you for developping this app, it so user friendly <3

**Comment by sdercolin** [comment]
Thank a lot for the feedback. Yes I think error handling for it is useful. Will have it fixed in the next release!

**Comment by sdercolin** [comment]
https://github.com/sdercolin/vlabeler/commit/1083c5a6bef09e5290ec035ad075bae00e0799b7

**Comment by sdercolin** [comment]
Fixed in https://github.com/sdercolin/vlabeler/releases/tag/1.0.0-alpha5

**Comment by KrankerApfel** [comment]
> Thank a lot for the feedback. Yes I think error handling for it is useful. Will have it fixed in the next release!

Your welcome ☺️

**Comment by KrankerApfel** [comment]
> Thank a lot for the feedback. Yes I think error handling for it is useful. Will have it fixed in the next release!

Your welcome ☺️
